# Generated by Django 3.0.6 on 2020-05-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Media',
        ),
    ]
