# Generated by Django 3.0.6 on 2020-05-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200530_1353'),
        ('media', '0007_auto_20200530_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='news_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_news', to='news.News'),
        ),
    ]
