# Generated by Django 3.0.6 on 2020-05-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20200526_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='picture',
        ),
    ]
