# Generated by Django 3.0.6 on 2020-05-26 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('news', '0002_auto_20200525_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.Source'),
        ),
    ]
