# Generated by Django 3.0.6 on 2020-05-26 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
