# Generated by Django 3.0.6 on 2020-05-27 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20200526_0528'),
        ('media', '0006_media_url'),
        ('news', '0008_auto_20200526_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_posted',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='news',
            name='media',
        ),
        migrations.AddField(
            model_name='news',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_media', to='media.Media'),
        ),
        migrations.RemoveField(
            model_name='news',
            name='source',
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.ManyToManyField(null=True, to='sources.Source'),
        ),
    ]
