# Generated by Django 3.0.6 on 2020-05-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20200530_1353'),
        ('sources', '0005_auto_20200530_1351'),
        ('news', '0009_auto_20200527_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=500, verbose_name='author name(s)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_posted',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='news',
            name='media',
        ),
        migrations.AddField(
            model_name='news',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, related_name='news_media', to='media.Media'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='news',
            name='source',
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.Source'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500, verbose_name='news title'),
        ),
    ]
