# Generated by Django 3.0.6 on 2020-05-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_auto_20200530_1446'),
        ('news', '0011_auto_20200530_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='news_media', to='media.Media'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
