# Generated by Django 3.0.6 on 2020-05-31 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_remove_news_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes_users',
        ),
        migrations.DeleteModel(
            name='LikeUsers',
        ),
    ]
