# Generated by Django 3.0.6 on 2020-05-30 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200528_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ops!, This email already exist.'}, max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Make sure your mail looks something like this: user@domain.com.', regex='(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)')], verbose_name='email address'),
        ),
    ]
