# Generated by Django 3.0.6 on 2020-05-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200530_1353'),
        ('users', '0005_auto_20200530_0237'),
    ]

    operations = [
    ]
