# Generated by Django 3.0.6 on 2020-05-31 17:09

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200531_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customusername',
            field=models.CharField(error_messages={'unique': 'Ops!, username already exists.'}, max_length=250, null=True, unique=True, verbose_name='My username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
