# Generated by Django 3.0.6 on 2020-05-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200531_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='customusername',
            new_name='nickname',
        ),
    ]
