# Generated by Django 3.0.6 on 2020-05-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200531_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': 'Ops!, username already exists.'}, max_length=250, null=True, unique=True, verbose_name='My nickname'),
        ),
    ]
