# Generated by Django 3.0.6 on 2020-05-26 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name_plural': 'Sources'},
        ),
    ]
