# Generated by Django 3.0.6 on 2020-05-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200526_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='modified',
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.DateTimeField(help_text='Date time when object was deleted', null=True, verbose_name='modified at'),
        ),
    ]
