# Generated by Django 3.0.6 on 2020-05-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20200526_0806'),
    ]

    operations = [
    ]
