# Generated by Django 3.0.6 on 2020-05-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'get_latest_by': 'created'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified',
        ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.DateTimeField(help_text='Date time when object was deleted', null=True, verbose_name='modified at'),
        ),
    ]
