# Generated by Django 3.0.6 on 2020-05-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_auto_20200530_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='feed_url',
            field=models.CharField(default='', max_length=2048, verbose_name='feed url'),
        ),
        migrations.AlterField(
            model_name='source',
            name='feed_type',
            field=models.CharField(choices=[('rss1', 'RSS1'), ('rss2', 'RSS2'), ('atom', 'ATOM'), ('html', 'HTML'), ('json', 'JSON')], default='rss2', max_length=4, verbose_name='feed type'),
        ),
    ]
