# Generated by Django 3.0.6 on 2020-05-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20200526_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='deleted',
            field=models.DateTimeField(blank=True, help_text='Date time when object was deleted', null=True, verbose_name='deleted at'),
        ),
    ]
