# Generated by Django 3.0.6 on 2020-05-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20200526_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
